# This is the main YAML file that references other pipeline files

name: Cloud CI/CD Pipeline

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check-out code in our repository
        uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
      - name: Build and Test
        uses: ./.github/workflows/build-and-test.yml
          path: .github/workflows/build-and-test.yml
